version: '3'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7.26
    # network_mode: "host" # 如果需要容器使用宿主机IP(内网IP)，则可以配置此项
    container_name: mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
    restart: unless-stopped # 设置容器自启模式
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
    environment:
    - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
    - MYSQL_ROOT_PASSWORD=123456 # 设置root密码
    volumes:
    - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
    - ./mysql/data:/var/lib/mysql/data # 映射数据库保存目录到宿主机，防止数据丢失
    - ./mysql/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
    ports:
    - "3305:3305"

  redis:
    hostname: redis
    image: redis:5.0.4
    container_name: redis
    restart: unless-stopped
    command: redis-server /etc/redis.conf # 启动redis命令
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
    - ./redis/data:/data
    - ./redis/redis.conf:/conf/redis.conf
    ports:
    - "6379:6379"