version: "3"
services:
  redis:
    container_name: redis-1
    image: redis:5.0.4
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/conf/redis.conf
    command: "/usr/local/bin/redis-server /conf/redis.conf"
